hw 7.2-7.4
js-tasks-ru/jsbasic-20240219_anna-nosova-int pull request #8
Opened 2024-03-27 16:27 UTC by AnnaNosova

очень криво получилось.
Стали падать тесты по предыдущим заданиям - по 5, 6 занятиям. С чем может быть связано?

2024-03-27 16:27 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-03-27 16:54 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-03-28 06:22 UTC, koalex requested changes
Исправить замечание в **7-3**. Из-за этого тесты и падают

2024-03-28 06:22 UTC, koalex commented on 7-module/3-task/index.js
> +    addEventListener('click', event => {
Опечатка
`this.elem.addEventListener('click', event => {`

2024-03-28 06:23 UTC, koalex commented
> очень криво получилось.
> Стали падать тесты по предыдущим заданиям - по 5, 6 занятиям. С чем может быть связано?

См. замечание в **7-3**

2024-03-28 11:39 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-03-28 11:41 UTC, AnnaNosova commented
Спасибо! Действительно, проглядела. 
Меня ещё в 7.4 смущает код. Вот эти 4 строки практически повторяются трижды:
this.value = Math.round(leftRelative * (this.steps - 1));
      this.sub('value').textContent = this.value;
      this.sub('progress').style.width = `${leftPercents}%`;
      this.sub('thumb').style.left = `${leftPercents}%`;

А вынести их в отдельный метод как-то не получилось

2024-03-29 05:35 UTC, koalex approved these changes

2024-03-29 05:35 UTC, koalex commented on 7-module/3-task/index.js
> +      console.log(valuePercents);
Зачем тут `console.log`? =)

2024-03-29 05:35 UTC, merged